### ISSUE TITLE
Conection Issues

### ISSUE THREAD

**Issue by rsp-git** [Manawyrm/ESP32_VirtualPrinter#1]
Hello,
I've built your project. I set up CUPS on a Virtual Machine and can create a PDF over telnet.
Now I have some issues with my ESP - Maybe it's the same reason, maybe not.
First:
I put it on a HM507 Scope with Parallel Interface. If the Scope is on the ESP doesn't get an IP, it hangs on "Waiting for WiFi... " with many dots. If I power off the Scope, the ESP Boots and get immediately an IP.
Then, when I start the scope, I get a char over LPT and so the ESP try to do a TCP Connection. This is not nice, but it is also no big problem.
When I Hit the Print Button, it starts with some Bytes and then Ends the Connection - then it connects again and transmit the rest. I've enabled the debug output on my Serial.
[esp32lpt1.txt](https://github.com/Manawyrm/ESP32_VirtualPrinter/files/14706116/esp32lpt1.txt)

Do you have an Idea?

Best Regards,
Raphael

**Comment by Manawyrm** [comment]
> If the Scope is on the ESP doesn't get an IP, it hangs on "Waiting for WiFi... " with many dots.
That's a very curious problem.
I wonder if there's either a noise issue or something related to some strapping pin we accidentally pulled around.

Would you be able to individually disconnect one of the wires after another and try if the ESP starts to connect successfully without one of them? 

Regarding the second connection close, maybe the 1s timeout in 
https://github.com/Manawyrm/ESP32_VirtualPrinter/blob/4e48cc2d31f65a07f84dc3c8f51abef379fd8bfa/src/main.cpp#L146
is too brief. Try 10sec instead.

**Comment by rsp-git** [comment]
Thanks for this hint - this works for me. I strugle also with cups but now i get good results.
I also build a Jumperbox for SUBD25 - and it is Pin 1 -> Strobe bzw. GPIO13 on ESP32 that interrupts booting.
When i disconnect it, it will boot.
I also tried to change the order and first set the GPIO and then do the WiFi stuff - but this doesn't work.

Maybe you have a Idea. GPIO13 is also ADC2/4 and HSPI_MOSI

**Comment by Manawyrm** [comment]
> it is Pin 1 -> Strobe bzw. GPIO13 on ESP32 that interrupts booting

huh! Wow, that is strange. I've double checked the datasheet and can't see any reason why that would happen.
Are you using a regular ESP32 board or something special?

In any case, the solution is clear: Pick another pin (not 0, 2, 4, 5, 12 or 15) and change the pin in the code accordingly.

Just out of curiousity: I've never seen a printout from a classic Hameg scope, can you share a "printout"? 😄

**Comment by rsp-git** [comment]
Hello,
now it Works. I modified the code a little bit and print a Case.
I also used the onboard LED to signal Wifi Search (blinking) and transmit (constant on while sending).
Maybe i'll try later to set the Scope to PCL to speed up.
I fork this project and then you can see the Changes and also the Prints :)
Thank you a lot.

**Comment by rsp-git** [comment]
So, done - everything is in my fork. Also the Cups Configs and so on - feel free to link to it, copy it or what ever.
Sorry, but now i throw the box behind my Scope and only remember to it if it won't work :)

**Comment by Manawyrm** [comment]
Oh, you built a nice case and everything! Very cool and neat! 😺

Regarding the Pin13 issue, I was just made aware of this thread, apparently Pin13 is also a JTAG pin and there seems to be some bug with that logic… 
https://forum.arduino.cc/t/esp32-gpio13-not-working-as-input-when-wifi-is-active/916137/3

Thank you for sharing the changes and the printout, love to see it :)
