### ISSUE TITLE
not an issue, just passing by..

### ISSUE THREAD

**Issue by thirstyone** [Manawyrm/ESP32_VirtualPrinter#2]
I wish someone managed a reverse task: print to an old usb printer (e.g. LJ1022) via wifi or ethernet (esp or stm)...

**Comment by Manawyrm** [comment]
Use a small Linux box (like a Raspberry Pi Zero, old OpenWRT router, etc.) with USB OTG and CUPS to do this job.

The printer drivers required for all sorts of different (especially "GDI" or WinPrinters) makes this a very tricky task to do in real embedded hardware.

In general, what you're describing is typically called "print server" and widely available from a whole bunch of vendors. Used units are often free in scrap piles. Routers can do this as well.

**Comment by thirstyone** [comment]
Yep, I know. Moreover, I have an openwrt-capable mr3020 at hand (you've just reminded me of it, thank you!) 
However, judging by reddit posts, i was not alone looking for an opensource print server design based on cheap microcontrollers. 
On the technical side: as far as I understand, CUPS is an open source project, which probably means it contains the source code for the printer driver, doesn't it? (Which could probably be reused?) So the task would be to make MCU pretend a usb host? Nevermind, just realized, U in CUPS stands for Unix, so it won't work on a barebone MCU, without Linux subsystems, and instead of taking the one that supports Linux and starting from scratch, it's easier to go with the RPi Zero.
